version: '3.9'

services:
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: user_service
    ports:
      - "5432:5432"

  user-service:
    build:
      context: ./user-service
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres-db
  
  task-service:
    build:
      context: ./task-service
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres-db

  notification-service:
    build:
      context: ./notification-service
    ports:
      - "8002:8002"
    environment:
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_HOSTNAME=${SMTP_HOSTNAME}
